spring:
  jackson:
    serialization:
      write-dates-as-timestamps: false
  main:
    banner-mode: off

simulation:
  # How much traffic lanes and cameras to simulate
  num-lanes: 3
  # Minimum and maximum delay before a new vehicle enters a lane (in milliseconds)
  entry-delay:
    minimum: 50
    maximum: 3000
  # Minimum and maximum delay after which a vehicle exits the lane (in seconds)
  exit-delay:
    minimum: 4
    maximum: 8

# Traffic Control Service configuration
# - For local development, use the default configuration => do not set anything
# - For Kubernetes cluster the name of the service can be set to TRAFFIC_CONTROL_SERVICE.
# - For Azure Container Apps with Ingress on Traffic Control Service or other deployments, you can use
#   TRAFFIC_CONTROL_SERVICE_BASE_URL to set the URL of the service
traffic-control.entry.address: ${TRAFFIC_CONTROL_SERVICE_BASE_URL:http://${TRAFFIC_CONTROL_SERVICE:localhost}:6000}/entrycam
traffic-control.exit.address: ${TRAFFIC_CONTROL_SERVICE_BASE_URL:http://${TRAFFIC_CONTROL_SERVICE:localhost}:6000}/exitcam
