apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub
spec:
  type: pubsub.redis
  version: v1
  metadata:
  - name: redisHost
    value: <replaceWithRedisHostName>:<replaceWithRedisSSLPort>
  - name: redisPassword
    value: <replaceWithPrimaryKey>
  - name: enableTLS
    value: "true"
scopes:
  - trafficcontrolservice
  - finecollectionservice