apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: vehicleregistrationservice
  name: vehicleregistrationservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vehicleregistrationservice
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: vehicleregistrationservice
      # annotations:
        # dapr.io/enabled: "true"
        # dapr.io/app-id: "vehicleregistrationservice"
        # dapr.io/app-port: "6002"
    spec:
      containers:
      - image: <REPLACE_WITH_CONTAINER_REGISTRY_NAME>.azurecr.io/vehicle-registration-service:latest
        name: vehicle-registration-service
        resources: {}
status: {}
